const fs = require('fs') 

const iconList = [
    "Airport_A_black.png",
    "Airport_A_white.png",
    "Airport_B_black.png",
    "Airport_B_white.png",
    "Airport_C_black.png",
    "Airport_C_white.png",
    "Airport_D_black.png",
    "Airport_D_white.png",
    "Airport_E_black.png",
    "Airport_E_white.png",
    "Animal_A_black.png",
    "Animal_A_white.png",
    "Animal_B_black.png",
    "Animal_B_white.png",
    "Archeological_Site_black.png",
    "Archeological_Site_white.png",
    "Artifact_black.png",
    "Artifact_white.png",
    "Bank_black.png",
    "Bank_white.png",
    "Battle_A_black.png",
    "Battle_A_white.png",
    "Battle_B_black.png",
    "Battle_B_white.png",
    "Building_B_black.png",
    "Building_B_white.png",
    "Bullring_black.png",
    "Bullring_white.png",
    "Capital_City_A_black.png",
    "Capital_City_A_white.png",
    "Capital_City_B_black.png",
    "Capital_City_B_white.png",
    "Capital_City_D_black.png",
    "Capital_City_D_white.png",
    "Castle_A_black.png",
    "Castle_A_white.png",
    "Castle_B_black.png",
    "Castle_B_white.png",
    "Castle_C_black.png",
    "Castle_C_white.png",
    "Castle_D_black.png",
    "Castle_D_white.png",
    "Church_A_black.png",
    "Church_A_white.png",
    "Church_B_black.png",
    "Church_B_white.png",
    "Church_C_black.png",
    "Church_C_white.png",
    "Conflict_black.png",
    "Conflict_white.png",
    "Factory_black.png",
    "Factory_white.png",
    "Fire_black.png",
    "Fire_white.png",
    "Fish_black.png",
    "Fish_white.png",
    "Hot_Air_Balloon_black.png",
    "Hot_Air_Balloon_white.png",
    "Hydroelectric_black.png",
    "Hydroelectric_white.png",
    "Lighthouse_black.png",
    "Lighthouse_white.png",
    "Mine_A_black.png",
    "Mine_A_white.png",
    "Mine_B_black.png",
    "Mine_B_white.png",
    "Modern Ship_black.png",
    "Modern Ship_white.png",
    "Monument_black.png",
    "Monument_white.png",
    "Native_A_black.png",
    "Native_A_white.png",
    "Native_American_Plains_Village_black.png",
    "Native_American_Plains_Village_white.png",
    "Oil_Well_A_black.png",
    "Oil_Well_A_white.png",
    "Oil_Well_B_black.png",
    "Oil_Well_B_white.png",
    "Oil_Well_C_black.png",
    "Oil_Well_C_white.png",
    "Parking_black.png",
    "Parking_white.png",
    "Pass_A_black.png",
    "Pass_A_white.png",
    "Pass_B_black.png",
    "Pass_B_white.png",
    "Peak_A_black.png",
    "Peak_A_white.png",
    "Peak_C_black.png",
    "Peak_C_white.png",
    "POI_A copy.png",
    "POI_A_black.png",
    "POI_C_black.png",
    "POI_C_white.png",
    "Pony_Express_black.png",
    "Pony_Express_white.png",
    "Port_black.png",
    "Port_white.png",
    "Sailling_Ship_B_black.png",
    "Sailling_Ship_B_white.png",
    "Ski_Area_A_black.png",
    "Ski_Area_A_white.png",
    "Ski_Area_B_black.png",
    "Ski_Area_B_white.png",
    "Sportfish_black.png",
    "Sportfish_white.png",
    "Square_black.png",
    "Square_white.png",
    "Steamboat_black.png",
    "Steamboat_white.png",
    "Tank_black.png",
    "Tank_white.png",
    "Temple_black.png",
    "Temple_white.png",
    "Townspot_A_black.png",
    "Townspot_A_white.png",
    "Townspot_B_black.png",
    "Townspot_B_white.png",
    "Townspot_C_black.png",
    "Townspot_C_white.png",
    "Townspot_D_black.png",
    "Townspot_D_white.png",
    "Townspot_E_black.png",
    "Townspot_E_white.png",
    "Treeline_black.png",
    "Triangle_black.png",
    "Triangle_white.png",
    "Uranium_black.png",
    "Uranium_white.png",
    "Waterfall_black.png",
    "Waterfall_white.png",
    "Winery_black.png",
    "Winery_white.png"
]

const targetArr = []

iconList.forEach((d, i) => {

    const targetColorObj = {}
    const sepSplit = d.split("_")
    const colorId = sepSplit[sepSplit.length-1].replace(".png", "")

    const id = d.toLowerCase().replace("_black", "").replace("_white", "").replace(".png","")

    targetColorObj[colorId] = d

    const foundObjIdx = targetArr.findIndex(t => t.id == id)
    if (foundObjIdx > -1) {
        Object.assign(targetArr[foundObjIdx].colors, targetColorObj)
    } else {
        targetArr.push({
            id: id,
            colors: targetColorObj
        })
    }


})

fs.writeFileSync("./src/data/icons.json", JSON.stringify(targetArr))
